webtalk_init -webtalk_dir C:/Users/demon/INTERNSHIP/src_sim_vivado/AXI_UART_/AXI_UART_.sim/sim_1/synth/func/xsim/xsim.dir/AXI_TOP_TEST_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jun 30 18:42:52 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212712012_0_0_748" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "69c9dbb4-e030-4e4d-b2bb-b8553b496d36" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3f17173f64fe45a1a8e11bf5232506a3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "20" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 5800H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3194 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "4 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "36.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "19076_KB" -context "xsim\\usage"
webtalk_transmit -clientid 887353233 -regid "212712012_0_0_748" -xml C:/Users/demon/INTERNSHIP/src_sim_vivado/AXI_UART_/AXI_UART_.sim/sim_1/synth/func/xsim/xsim.dir/AXI_TOP_TEST_func_synth/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/demon/INTERNSHIP/src_sim_vivado/AXI_UART_/AXI_UART_.sim/sim_1/synth/func/xsim/xsim.dir/AXI_TOP_TEST_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/demon/INTERNSHIP/src_sim_vivado/AXI_UART_/AXI_UART_.sim/sim_1/synth/func/xsim/xsim.dir/AXI_TOP_TEST_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
