# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k410tlfbv676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/demon/INTERNSHIP/src_sim_vivado/AXI_UART_/AXI_UART_.cache/wt [current_project]
set_property parent.project_path C:/Users/demon/INTERNSHIP/src_sim_vivado/AXI_UART_/AXI_UART_.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/demon/INTERNSHIP/src_sim_vivado/AXI_UART_/AXI_UART_.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/demon/INTERNSHIP/src_sim_vivado/AXI_UART_/AXI_UART_.srcs/sources_1/imports/new/AR_FIFO.v
  C:/Users/demon/INTERNSHIP/src_sim_vivado/AXI_UART_/AXI_UART_.srcs/sources_1/imports/new/AW_FIFO.v
  C:/Users/demon/INTERNSHIP/src_sim_vivado/AXI_UART_/AXI_UART_.srcs/sources_1/imports/new/AXI_MASTER.v
  C:/Users/demon/INTERNSHIP/src_sim_vivado/AXI_UART_/AXI_UART_.srcs/sources_1/imports/new/BAUD_GENRATOR.v
  C:/Users/demon/INTERNSHIP/src_sim_vivado/AXI_UART_/AXI_UART_.srcs/sources_1/imports/new/FIFO.v
  C:/Users/demon/INTERNSHIP/src_sim_vivado/AXI_UART_/AXI_UART_.srcs/sources_1/imports/new/READ_BUFFER.v
  C:/Users/demon/INTERNSHIP/src_sim_vivado/AXI_UART_/AXI_UART_.srcs/sources_1/imports/new/READ_BUFFER_CONTROLLER.v
  C:/Users/demon/INTERNSHIP/src_sim_vivado/AXI_UART_/AXI_UART_.srcs/sources_1/imports/new/TIMER.v
  C:/Users/demon/INTERNSHIP/src_sim_vivado/AXI_UART_/AXI_UART_.srcs/sources_1/imports/new/UART_CONTROLLER.v
  C:/Users/demon/INTERNSHIP/src_sim_vivado/AXI_UART_/AXI_UART_.srcs/sources_1/imports/new/UART_FIFO.v
  C:/Users/demon/INTERNSHIP/src_sim_vivado/AXI_UART_/AXI_UART_.srcs/sources_1/imports/new/WRITE_BUFFER_CONTROLLER.v
  C:/Users/demon/INTERNSHIP/src_sim_vivado/AXI_UART_/AXI_UART_.srcs/sources_1/imports/new/WRITE_CONTROLLER.v
  C:/Users/demon/INTERNSHIP/src_sim_vivado/AXI_UART_/AXI_UART_.srcs/sources_1/imports/new/W_FIFO.v
  C:/Users/demon/INTERNSHIP/src_sim_vivado/AXI_UART_/AXI_UART_.srcs/sources_1/imports/new/AXI_MASTER_WRAPPER.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/demon/INTERNSHIP/src_sim_vivado/AXI_UART_/AXI_UART_.srcs/constrs_1/new/AXI_UART.xdc
set_property used_in_implementation false [get_files C:/Users/demon/INTERNSHIP/src_sim_vivado/AXI_UART_/AXI_UART_.srcs/constrs_1/new/AXI_UART.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top AXI_TOP_WRAPPER -part xc7k410tlfbv676-2L -flatten_hierarchy none


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef AXI_TOP_WRAPPER.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file AXI_TOP_WRAPPER_utilization_synth.rpt -pb AXI_TOP_WRAPPER_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
